Translations update from Weblate
wallabag/android-app pull request #1064
Opened 2020-09-30 10:04 UTC by weblate

Translations update from [Weblate](https://hosted.weblate.org/projects/wallabag/android-app/) for wallabag/Android App.

Current translation status:

![Weblate translation status](https://hosted.weblate.org/widgets/wallabag/-/android-app/horizontal-auto.svg)

2020-10-05 09:20 UTC, tcitworld submitted a review, later dismissed

2020-10-05 09:22 UTC, tcitworld requested changes

2020-10-05 09:22 UTC, tcitworld commented on app/src/main/res/values-fa/strings.xml
> +    <string name="downloadAsFileProgress">والابگ مقاله شما را در %2$s بارگیری می‌کند</string>
There's an issue here.

2020-10-12 10:33 UTC, di72nn approved these changes
I fixed one Persian string, CI is ok now.

I haven't checked the translations though.

2020-10-12 14:47 UTC, tcitworld approved these changes

2020-10-12 14:47 UTC, merged