Article header style tweak
wallabag/android-app pull request #1198
Opened 2021-09-07 00:35 UTC by cheywood

I've had a go at making a minor style tweak to the top area of the article. There's no issue created for these changes -  sorry if this is presumptuous or you'd rather a different workflow! Let me know.

These changes:
- Use material icons for stats at the top of the article, ala Wallabag web. It no longer displays the pixelated globe icon for the domain and the icon/s now better match the theme (no white square background for dark themes).
- Slightly increase spacing in header area. Things seemed a bit cramped to me (in these days on these bigger devices with all this space). This also provides a clearer separation between header/stats and article content. Again, now closer to the web design.

There's a mechanism in use to retain the reading of the estimated time label for TTS, and an attempt has been made to transfer the existing translations for that. A shared CSS file has been added, but I can see that doing it this way reduces the capacity to theme those items (but reduces lots of duplication). Let me know and I can duplicate more of it if that's preferred. The icon font declaration being shared I think at least makes sense.

After
![image](https://user-images.githubusercontent.com/31988069/132267890-e4a2fd2f-402a-4cbd-a9a0-a60a8d8cabf8.png)

Before
![Screenshot_20210907-095341_wallabag](https://user-images.githubusercontent.com/31988069/132267912-b03280d9-61af-4298-aa91-8bf188dc4e39.png)

After
![Screenshot_20210907-095533_wallabag](https://user-images.githubusercontent.com/31988069/132267935-04685e37-91b2-4b45-8637-1f5f88015619.png)

Before
![Screenshot_20210907-095530_wallabag](https://user-images.githubusercontent.com/31988069/132267944-3a23478c-7012-4d2f-bb76-c4da9c737093.png)

2021-09-07 08:53 UTC, di72nn commented
Thank you, that's a welcome contribution!
I'll try to have a look at the implementation soon.

2021-09-07 10:46 UTC, cheywood commented
Great, thanks!

2021-09-26 15:46 UTC, di72nn requested changes
Sorry for the delay.

Apart from other remarks, this seemed not to work on older Android versions: I tried it on Android 5, 6, and 7 emulators. Didn't find anything useful in logs.
Having the font in `assets` may make a difference, but I only tested it on some of these Android versions (didn't work either).

2021-09-26 15:46 UTC, di72nn commented on app/src/main/res/raw/webview_htmlbase.html
> -						<img id="domainimg" alt="%5$s" src="file:///android_asset/ic_action_web_site.png" />
`ic_action_web_site.png` can be removed.

2021-09-26 15:46 UTC, di72nn commented on app/src/main/java/fr/gaulupeau/apps/Poche/ui/ReadArticleActivity.java
> +                 .append(android.text.format.DateFormat.getTimeFormat(this).format(publishedAt));
This is a very minor issue, but the indentation here is wrong (5 spaces (compared to the previous line) instead of 8).

2021-09-26 15:46 UTC, di72nn commented on app/src/main/java/fr/gaulupeau/apps/Poche/ui/ReadArticleActivity.java
> +             .append("</span>");
Indentation.

2021-09-26 15:46 UTC, di72nn commented on app/src/main/java/fr/gaulupeau/apps/Poche/ui/ReadArticleActivity.java
> +                     .append("</a>");
Indentation.

2021-09-26 15:46 UTC, di72nn commented on app/src/main/assets/shared.css
> +  src: url(file:///android_res/raw/materialicons_regular.ttf) format('truetype');
I would prefer to move the file to `assets` and simply use `url('materialicons_regular.ttf')` here.

2021-10-19 04:42 UTC, cheywood commented
> Sorry for the delay.
> 
> Apart from other remarks, this seemed not to work on older Android versions: I tried it on Android 5, 6, and 7 emulators. Didn't find anything useful in logs. Having the font in `assets` may make a difference, but I only tested it on some of these Android versions (didn't work either).

Sorry for the slow response. Just letting you know that I will get onto this, I just got buried in other things. Hopefully time soon.

2021-11-01 19:50 UTC, Strubbl requested changes
this is very nice improvement of the article view. I found a typo only

2021-11-01 19:50 UTC, Strubbl commented on app/src/main/res/raw/tts_parser.js
> +        || (element.tagName === 'I' && element.classList.contains('no-tss'));
no-tss is a typo and should be named "no-tts", or?

2021-11-01 19:50 UTC, Strubbl commented on app/src/main/res/raw/webview_htmlbase.html
> +                              <i class="material-icons no-tss">link</i>
no-tss -> no-tts

2021-11-01 19:52 UTC, Strubbl commented
To have a more complete picture of the article view, can you also please check that article's tags are displayed correctly? in your screenshots the articles have no tags assigned. Maybe you can add some for testing?

2021-11-02 02:40 UTC, cheywood commented
Thanks @Strubbl, good pickup!

I've just pushed changes aimed at addressing all the raised issues from both of you. Older device fix is described in the commit message. Also when creating the screenshots with tags below I made some minor tweaks to the tag styling, adding a little more spacing, ala the rest of the PR.

After
![Screenshot_20211102-115639_wallabag](https://user-images.githubusercontent.com/31988069/139777413-af81c38b-7ebb-43ce-84c2-c4f85d7eea69.png)

Before
![Screenshot_20211102-115636_wallabag](https://user-images.githubusercontent.com/31988069/139777429-7685267a-3195-40c6-880d-e087f47a1ead.png)

2021-11-04 19:25 UTC, Strubbl approved these changes

2021-11-04 19:26 UTC, Strubbl commented
This PR just needs to be rebased. Do you need help with that?

2021-11-05 02:17 UTC, cheywood commented
No, thanks @Strubbl that should be rebased now. Let me know if you want it squashed (or I'm fine if that'd done while merging).

2021-11-20 11:11 UTC, di72nn requested changes
Thanks for addressing the issues! And sorry for the delay.

It seems something broke the TTS parsing:
```
D/WebView.onCM: Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'. @ 257: file:///android_asset/
D/WebViewText: onDocumentParseStart()
V/WebViewText: onDocumentParseText(<Article title text>, 57.000000, 296.000092)
```
Can you please look into it?

`app/src/main/res/raw/materialicons_regular.ttf` should be removed now.

And what is the source of `app/src/main/assets/MaterialIcons-Regular.ttf`? The previous file is [from here](https://github.com/google/material-design-icons/blob/ab12f16d050ecb1886b606f08825d24b30acafea/font/MaterialIcons-Regular.ttf) (it got updated recently, BTW), but the new one is half the size compared to it - does it need any special treatment?

I would squash most of the stuff into the first commit, leaving only the "Attempt to update translations ..." and "Minor tweaks to tags styling in article" commits separate.

2022-01-05 03:53 UTC, cheywood commented
Hi, sorry again for the delay this end.

The TTS parsing issue is now fixed, `app/src/main/res/raw/materialicons_regular.ttf` removed and commits squashed.

No special treatment for the font file but it looks like I was somehow using the version from the Material Icons v3.0.1 release (maybe [from here](http://google.github.io/material-design-icons/#getting-icons), that seems to point to the older release). I've now updated it to the version in the latest release (v4.0.0).

2022-01-06 11:30 UTC, Strubbl commented
LGTM, thank you :rocket:

2022-01-09 07:54 UTC, di72nn approved these changes
Looks good.

// I updated the second commit to remove two `articleContent_globeIconAltText` strings from new translations.

2022-01-09 07:55 UTC, merged

2022-01-09 07:55 UTC, di72nn commented
Thanks a lot!

2022-01-12 00:25 UTC, cheywood commented
My pleasure! Sorry again for all the delays and relative looseness :slightly_smiling_face: